basePath: /swagger/
host: localhost:8085
info:
  contact: {}
  description: API для управления пользователями
  title: TestUser API
  version: "0.5"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
